<div class="row">
    <div class="col-4">
        <form name="addData" method="post" id="addData" class="form"
              action="<?php echo $this->getFormAction(); ?>"
              data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>"
              data-mage-init='{"validation":{}}'>
            <fieldset class="fieldset">
                <legend class="legend"><span><?= $block->escapeHtmlAttr(__('Add new word')) ?></span></legend>
                <fieldset class="fieldset row">
                    <div class="fields col-4 bg-primary">
                        <div class="field name required">
                            <label class="label" for="title"><span><?= $block->
                                    escapeHtmlAttr(__('Word')) ?></span></label>
                            <div class="control">
                                <input name="word" id="word" title="Word" class="input-text" type="text"
                                       data-validate="{required:true}">
                            </div>
                        </div>
                        <div class="field name required">
                            <label class="label" for="title"><span><?= $block->escapeHtmlAttr(__('Word-class')) ?></span></label>
                            <div class="control">
                                <input name="email" id="meaning" title="Email" value="" class="input-text validate-length" type="text"
                                       data-validate="{required:true, 'min_text_length':'1'}" />
                            </div>
                        </div>
                        <div class="field name required">
                            <label class="label" for="title"><span><?= $block->escapeHtmlAttr(__('Meaning')) ?></span></label>
                            <div class="control">
                                <textarea name="meaning" id="meaning" title="Meaning" class="input-text validate-length" type="textarea"
                                       rows="4" cols="50"
                                       data-validate="{required:true, 'min_text_length':'1'}"></textarea>
                            </div>
                        </div>
                    </div>
                </fieldset>
            </fieldset>
            <div class="actions-toolbar">
                <div class="primary">
                    <button type="submit" class="action submit primary" title="Save"><span><?= $block->
                            escapeHtmlAttr(__('Save')) ?></span></button>
                </div>
            </div>
        </form>
    </div>
</div>
